[package]
name = "bevy_vrm"
description = "Bevy plugin for loading VRM avatars."
keywords = ["bevy", "vrm"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy.workspace = true
bevy_gltf_kun = { version = "0.0.12", default-features = false, features = ["import"] }
bevy_shader_mtoon.workspace = true
gltf_kun.workspace = true
gltf_kun_vrm.workspace = true
serde.workspace = true
serde_vrm.workspace = true
thiserror.workspace = true
bevy_transform_gizmo = "0.11.0"
bevy_mod_picking = "0.18.2"
bevy-inspector-egui = "0.24.0"
random-number = "0.1.8"

[dev-dependencies]
bevy = "0.13.0"
bevy_egui.workspace = true
bevy_panorbit_camera.workspace = true
